
POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "acohen89", "first_name": "adam", "last_name": "Cohen", "password": "Pass1234!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "adameco", "password": "CohenWifi##800" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 5862c5c587b5de5d2384d0f8f04bf2a789e7b52e

###
GET http://127.0.0.1:8000/recipe/get_reicpe
Content-Type: application/json
Authorization: token 5862c5c587b5de5d2384d0f8f04bf2a789e7b52e

{ "id": 86 }

###
POST http://127.0.0.1:8000/recipe/create_recipe
Content-Type: application/json
Authorization: token 5862c5c587b5de5d2384d0f8f04bf2a789e7b52e

{
    "userId": 1, 
    "beginningRecipe": true, 
    "title": "Finished Recipe",  
    "created": "2024-04-11T10:00:00Z",  
    "last_edited": "2024-04-11T12:00:00Z", 
    "ingredients": [
        "200g spaghetti", 
        "1 onion",
        "400g canned tomatoes",
        "Salt", "Black pepper"
    ],
    "image_url": "https://example.com/spaghetti-bolognese.jpg", 
    "procedure": [
        "Cook spaghetti according to package directions.",  
        "In a pan, cook the minced beef until browned.",
        "Add chopped onion and garlic, cook until softened.",
        "Add tomatoes, tomato paste, and seasonings. Simmer.",
        "Serve sauce over spaghetti."
    ],
    "notes": "Garnish with fresh basil and grated Parmesan cheese.", 
    "in_progress": false,
    "parentRID": null
}
