# Generated by Django 3.2.16 on 2024-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipes',
            name='recipesId',
        ),
        migrations.AddField(
            model_name='userrecipes',
            name='recipesId',
            field=models.ManyToManyField(default=None, to='recipe.Recipe'),
        ),
    ]
