# Generated by Django 4.2.11 on 2024-04-21 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0002_auto_20240420_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrecipes",
            name="userId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="userId",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
