# Generated by Django 4.2.11 on 2024-04-25 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0003_alter_userrecipes_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="beginningRecipe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe", name="image_url", field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe", name="notes", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="parentRID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_recipes",
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="iteration_ids",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iterations",
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userrecipes",
            name="userId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="userRecipes",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
