# Generated by Django 4.2.11 on 2024-04-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipe_beginningrecipe_recipe_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="iteration_ids",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iterations",
                to="recipe.recipe",
            ),
        ),
    ]
