# Generated by Django 4.2.11 on 2024-05-19 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipe_iteration_ids_recipe_iteration_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None),
        ),
    ]
